export const THEME = {
    light: {
        background: "#fff",
        text: "#000",
        primary: "#0275d8",
        secondary: "#6c757d",
        success: "#5cb85c",
        danger: "#d9534f",
        warning: "#f0ad4e",
        info: "#5bc0de",
        activeLink: "red",
        // appname color  gold
        appname: "#A67C00",
        input: "#f0ad4e",
        form: "#000",
        label: "white",
        btnSign: "#f0ad4e",
        btnSignText: "black",
    },
    dark: {
        background: "#000",
        text: "#fff",
        primary: "#0275d8",
        secondary: "#6c757d",
        success: "#5cb85c",
        danger: "#d9534f",
        warning: "#f0ad4e",
        info: "#5bc0de",
        activeLink: "red",
        appname: "#A67C00",
        input: "#000",
        form: "#f0ad4e",
        label: "black",
        btnSign: "black",
        btnSignText: "white",
    },
};
